export const mockUser = {
  id: "user_1",
  name: "Emanuel Hotea",
  email: "emanuelhotea1@gmail.com",
  image: null,
  isPro: true,
};

export const mockItemTypes = [
  { id: "type_1", name: "Snippet", slug: "snippets", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_2", name: "Prompt", slug: "prompts", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_3", name: "Note", slug: "notes", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_4", name: "Command", slug: "commands", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_5", name: "Link", slug: "links", icon: "Link", color: "#10b981", isSystem: true },
  { id: "type_6", name: "File", slug: "files", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_7", name: "Image", slug: "images", icon: "Image", color: "#ec4899", isSystem: true },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useLocalStorage hook",
    contentKind: "TEXT",
    content: `import { useState, useEffect } from "react";\n\nexport function useLocalStorage<T>(key: string, initial: T) {\n  const [value, setValue] = useState<T>(initial);\n\n  useEffect(() => {\n    const stored = localStorage.getItem(key);\n    if (stored) setValue(JSON.parse(stored));\n  }, [key]);\n\n  const set = (val: T) => {\n    setValue(val);\n    localStorage.setItem(key, JSON.stringify(val));\n  };\n\n  return [value, set] as const;\n}`,
    language: "typescript",
    description: "Custom hook for syncing state with localStorage",
    isFavorite: true,
    isPinned: false,
    itemTypeId: "type_1",
    tags: ["react", "hooks", "localStorage"],
    collections: ["col_1"],
    lastUsedAt: "2026-06-13T10:00:00Z",
    createdAt: "2026-06-01T09:00:00Z",
  },
  {
    id: "item_2",
    title: "Senior dev code review prompt",
    contentKind: "TEXT",
    content: "You are a senior software engineer. Review the following code for: correctness, security issues, performance problems, and maintainability. Be direct and specific. Point out what's good and what needs improvement.",
    language: null,
    description: "Prompt for AI code review",
    isFavorite: true,
    isPinned: true,
    itemTypeId: "type_2",
    tags: ["ai", "code-review"],
    collections: ["col_2"],
    lastUsedAt: "2026-06-13T09:30:00Z",
    createdAt: "2026-05-20T14:00:00Z",
  },
  {
    id: "item_3",
    title: "Docker cleanup commands",
    contentKind: "TEXT",
    content: "docker system prune -a --volumes",
    language: "bash",
    description: "Remove all unused Docker resources",
    isFavorite: false,
    isPinned: false,
    itemTypeId: "type_4",
    tags: ["docker", "devops"],
    collections: ["col_3"],
    lastUsedAt: "2026-06-12T16:00:00Z",
    createdAt: "2026-05-15T11:00:00Z",
  },
  {
    id: "item_4",
    title: "Tailwind CSS v4 docs",
    contentKind: "URL",
    content: null,
    url: "https://tailwindcss.com/docs",
    language: null,
    description: "Official Tailwind CSS v4 documentation",
    isFavorite: false,
    isPinned: false,
    itemTypeId: "type_5",
    tags: ["tailwind", "css", "docs"],
    collections: ["col_1"],
    lastUsedAt: "2026-06-11T08:00:00Z",
    createdAt: "2026-05-10T10:00:00Z",
  },
  {
    id: "item_5",
    title: "API error handling note",
    contentKind: "TEXT",
    content: "Always return `{ success, data, error }` from server actions. Use toast for user-facing errors. Log full error server-side, never expose internals to client.",
    language: null,
    description: "Error handling conventions",
    isFavorite: false,
    isPinned: false,
    itemTypeId: "type_3",
    tags: ["conventions", "api"],
    collections: ["col_2"],
    lastUsedAt: "2026-06-10T14:00:00Z",
    createdAt: "2026-05-05T09:00:00Z",
  },
  {
    id: "item_6",
    title: "git stash with message",
    contentKind: "TEXT",
    content: "git stash push -m \"WIP: feature description\"",
    language: "bash",
    description: "Stash changes with a descriptive message",
    isFavorite: false,
    isPinned: false,
    itemTypeId: "type_4",
    tags: ["git"],
    collections: ["col_3"],
    lastUsedAt: "2026-06-09T11:00:00Z",
    createdAt: "2026-04-20T10:00:00Z",
  },
  {
    id: "item_7",
    title: "Prisma find with relations",
    contentKind: "TEXT",
    content: `const user = await prisma.user.findUnique({\n  where: { id },\n  include: {\n    items: { include: { itemType: true, tags: { include: { tag: true } } } },\n    collections: true,\n  },\n});`,
    language: "typescript",
    description: "Prisma query with nested includes",
    isFavorite: true,
    isPinned: false,
    itemTypeId: "type_1",
    tags: ["prisma", "database", "typescript"],
    collections: ["col_1", "col_2"],
    lastUsedAt: "2026-06-08T13:00:00Z",
    createdAt: "2026-04-15T09:00:00Z",
  },
  {
    id: "item_8",
    title: "Explain like I'm a junior dev",
    contentKind: "TEXT",
    content: "Explain the following concept as if I am a junior developer with 1 year of experience. Use simple analogies, avoid jargon, and give a concrete example.",
    language: null,
    description: "Teaching-style explanation prompt",
    isFavorite: false,
    isPinned: false,
    itemTypeId: "type_2",
    tags: ["ai", "learning"],
    collections: ["col_2"],
    lastUsedAt: "2026-06-07T10:00:00Z",
    createdAt: "2026-04-10T14:00:00Z",
  },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Reusable React hooks, patterns, and component templates",
    isFavorite: true,
    itemCount: 3,
    dominantTypeColor: "#3b82f6",
    createdAt: "2026-05-01T09:00:00Z",
  },
  {
    id: "col_2",
    name: "AI Prompts",
    description: "Curated prompts for coding, review, and learning",
    isFavorite: true,
    itemCount: 4,
    dominantTypeColor: "#8b5cf6",
    createdAt: "2026-05-05T10:00:00Z",
  },
  {
    id: "col_3",
    name: "DevOps Commands",
    description: "Docker, git, and shell commands I always forget",
    isFavorite: false,
    itemCount: 2,
    dominantTypeColor: "#f97316",
    createdAt: "2026-05-10T11:00:00Z",
  },
];
